### PR TITLE
Added new test data, data objects are now created in correct order.

### PR DESCRIPTION
**Pull request by sifudiep**

### CODE REVIEW

**Review by joelAndreasson — CHANGES_REQUESTED** [review]
It would be REALLY nice if switching between local DB and live DB can be done via an .env variable, especially since teams outside of the backend tribe will be using the backend repo to test against a local DB :)

**Comment by LasseLejon** [comment]
> It would be REALLY nice if switching between local DB and live DB can be done via an .env variable, especially since teams outside of the backend tribe will be using the backend repo to test against a local DB :)

I agree, this would be really useful for other teams just changing a variable. Also way less problems with accidentally pushing changes using local db to the aws server.

**Comment by sifudiep** [comment]
@joelAndreasson Har fixat environment variabler och kommenterat ut postgis raden :D

**Comment by LasseLejon** [comment]
> @joelAndreasson Har fixat environment variabler och kommenterat ut postgis raden :D

Nice 👍

**Review by joelAndreasson — APPROVED** [review]
Snyggt!

**Review by LasseLejon — APPROVED** [review]

**Pull request merged**
